spring:
  application:
    name: ecommerce-backend
  datasource:
    url: jdbc:h2:mem:ecommerce;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false

server:
  port: 8080
